"""add_checkout_and_device_binding

Revision ID: e3c9a6ba44ac
Revises: 276f16339169
Create Date: 2026-04-19 16:22:29.010327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e3c9a6ba44ac'
down_revision: Union[str, None] = '276f16339169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    check_status_enum = postgresql.ENUM(
        "checked_in",
        "checked_out",
        name="checkstatus",
        create_type=False,
    )
    check_status_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('device_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('device_token', sa.String(length=255), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=True),
    sa.Column('bound_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_bindings_device_token'), 'device_bindings', ['device_token'], unique=True)
    op.create_index(op.f('ix_device_bindings_employee_id'), 'device_bindings', ['employee_id'], unique=False)
    op.add_column(
        'attendance',
        sa.Column(
            'check_status',
            check_status_enum,
            nullable=False,
            server_default='checked_in',
        ),
    )
    op.add_column('attendance', sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('attendance', sa.Column('hours_clocked', sa.Float(), nullable=True))
    op.alter_column('attendance', 'check_status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    check_status_enum = postgresql.ENUM(
        "checked_in",
        "checked_out",
        name="checkstatus",
        create_type=False,
    )

    op.drop_column('attendance', 'hours_clocked')
    op.drop_column('attendance', 'checked_out_at')
    op.drop_column('attendance', 'check_status')
    op.drop_index(op.f('ix_device_bindings_employee_id'), table_name='device_bindings')
    op.drop_index(op.f('ix_device_bindings_device_token'), table_name='device_bindings')
    op.drop_table('device_bindings')
    check_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
